# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jonghyun Kim
name: Jonghyun Kim
position: Sr. Research Scientist
email: eluardkim@gmail.com
description: |
  I am a Sr. Research Scientist at [NVIDIA](https://www.nvidia.com/) working on near-eye displays and holographic displays for AR/VR applications.
  I was previously a Visiting Scholar at [Stanford University](https://www.stanford.edu/) in the Computational Imaging lab with Prof. Gordon Wetzstein.

  I received my Ph.D in Electrical and Computer Engineering from [Seoul National University](https://www.snu.ac.kr/) in 2017 where I was advised by
  Prof. Byoungho Lee, and my Bachelor's degree in Electrical Engineering from Seoul National University in 2011.

  My research interests include Near-eye Displays, Holographic Displays, Light Field Displays, and Computational Displays.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://research.nvidia.com/person/jonghyun-kim/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: 
google_scholar: QKsqzVEAAAAJ
google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
